# Generated by Django 3.2.20 on 2023-08-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
    ]
